dirList = {'E:\Alexis_Brainstorm\EOR21_Earley_Paper_Final\Final_Testing_Structs_and_Graphs\OHI\Default_Parameters\Step6F_Output\Omni', ...
    'E:\Alexis_Brainstorm\EOR21_Earley_Paper_Final\Final_Testing_Structs_and_Graphs\OHI\Default_Parameters\Step6F_Output\UltraZoom', ...
    'E:\Alexis_Brainstorm\EOR21_Earley_Paper_Final\Final_Testing_Structs_and_Graphs\OHI\Default_Parameters\Step6F_Output\Unaided', ... 
    'E:\Alexis_Brainstorm\EOR21_Earley_Paper_Final\Final_Testing_Structs_and_Graphs\ONH\Default_Parameters\Step6F_Output\Unaided'};
dirNames = {'OHI Omni', 'OHI UltraZoom', 'OHI Unaided', 'ONH Unaided'};
outputDir = 'E:\Alexis_Brainstorm\EOR21_Earley_Paper_Final\Final_Testing_Structs_and_Graphs\CombinedGraphs\Step7GraphCompareGroups';