% TO DO - select new sFiles at end

% Perform normal brainstorm steps
% Move to folder based on file name w/in subject

sFilesNew = [];
for i = 1:length(sFiles)
    sFile = sFiles(i);

    subjName = sFile.SubjectName;
    oldFile = sFile.Comment;
    oldFolder = sFile.Condition;
    oldFolder = oldFolder(5:end);
    newFolder = ['Epochs_', oldFolder, '_', oldFile];

    if contains(oldFile, 'Attend') 
        events = '1_N,2_N,3_N,4_N,5_N,6_N,7_N,8_N,9_N,10_N,11_N,12_N,13_N,14_N,15_N,16_N,17_N,18_N,19_N,20_N,21_N,22_N,23_N,24_N,25_N,1_Y,2_Y,3_Y,4_Y,5_Y,6_Y,7_Y,8_Y,9_Y,10_Y,11_Y,12_Y,13_Y,14_Y,15_Y,16_Y,17_Y,18_Y,19_Y,20_Y,21_Y,22_Y,23_Y,24_Y,25_Y';
    else
        events = '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,50,60';
    end

    if ~contains(oldFile, 'Ignore') 
     % Process: Import MEG/EEG: Events
    sFile = bst_process('CallProcess', 'process_import_data_event', sFile, [], ...
        'subjectname',   subjName, ...
        'condition',     newFolder, ...
        'eventname',     events, ...
        'timewindow',    [], ...
        'epochtime',     [-0.1, 2], ...
        'createcond',    0, ...
        'ignoreshort',   1, ...
        'usectfcomp',    1, ...
        'usessp',        1, ...
        'freq',          ...
        [], ...
        'baseline',      [-0.1, -0.002], ...
        'blsensortypes', 'EEG');
    
        % Process: Remove linear trend: [-100ms,2000ms]
        sFile = bst_process('CallProcess', 'process_detrend', sFile, [], ...
            'timewindow',  [-0.1, 2], ...
            'sensortypes', 'EEG', ...
            'overwrite',   1);

    end

end